### PR TITLE
Fixed a bug with Mekanism Pipes

### PR DESCRIPTION
**Pull request by TheCutter**
Added rainCollectorRange

### CODE REVIEW

**Review by lucsoft — APPROVED** [review]
LGTM

**Comment by Terpo** [comment]
Even if I don't like this solution for the pipes I will merge it. Normally in 1.12 a mod should first call hasCapability and after that call getCapability. 

Thanks for the range fix.

**Comment by TheCutter** [comment]
Thanks! Don't know if only Mekanism has the problem, but I put a CollectorBlock next to an existing Mechanical Pipe and the server crashed. I was not able to restart the server until I fixed the check.
I think the additional check doesn't hurt. :)

BTW nice mod for modpacks with finite water. I combined it with my own mod which syncs time and weather to my real time and weather. I'm happy it is raining today in Germany.

**Comment by Terpo** [comment]
Saxony is awaiting some rain too. But yeah. It is basically a NPE at this point in the code. 
Download: https://www.curseforge.com/minecraft/mc-mods/waterworks/files/2942595

**Pull request merged**
